#!/bin/sh

# Shutdown xendomains
if [ -d /proc/xen ]; then
  if [ -x /etc/rc.d/rc.xendomains ]; then
    echo "Stopping XEN domains:  /etc/rc.d/rc.xendomains"
    /etc/rc.d/rc.xendomains stop
  fi
  rm -r /etc/xen/auto/*
fi
